### ISSUE TITLE
把贡献者名单加入到帮助页

### ISSUE THREAD

**Issue by ztl8702** [zingzeu/yngdieng#313]
把贡献者名单加入到帮助页； 或者另建立一页（不然帮助页可能内容太长）。

包括：
* 长期活跃的词库编辑
* 录入工作统筹、校对者
* 其他录入志愿者

**Comment by Guanchishan** [comment]
贡献者名号有无打算以词条为单位显示于词条之下？

**Comment by ztl8702** [comment]
> 贡献者名号有无打算以词条为单位显示于词条之下？

contrib 的话是需要以词条为单位显示的。录入志愿者就不特地区分谁负责哪个部分了。

**Comment by ztl8702** [comment]
contrib其实就类似于维基。

**Comment by Guanchishan** [comment]
> > 贡献者名号有无打算以词条为单位显示于词条之下？
> 
> contrib 的话是需要以词条为单位显示的。录入志愿者就不特地区分谁负责哪个部分了。

不过鼓楼俗语我当初是有以条为单位记录志愿者贡献的，当然也有总的名单。要不然能具体到条的具体到条，不然则直接开总的名单，不强求再回溯到条如何。

**Comment by ztl8702** [comment]
> 要不然能具体到条的具体到条，不然则直接开总的名单，不强求再回溯到条如何。

对。就是这个意思。数据已经有分到每条的我们可以利用，没有分的不用再去花这个精力。

**Comment by ztl8702** [comment]
李版志愿者名单：
```

志愿者
--
叶伟
Vasopressin
miumiu想要miumiu
Nairoj
Monody
聂森浩
北海虽赊
瑾瑜
井井
陈明智
山月
250
Vasopressin
miumiu想要miumiu
子善
serendipity+泽生
简兮
叶伟
屑
陈毓灵
姜昕宜
洪兆益
loony/李嘉颖
spongebob
obliviate
怀堇
吴俊达
屑
菊仙
洪佳
BunnyBU
李火锅
羽岳/周思琦
L

```

李版统筹者：泽生 @Uoeuqui

**Comment by Guanchishan** [comment]
> 关彳山

我想把自己的署名从山月改为关彳山。已经把上一楼的名单自行改了。可以吗？

**Comment by ztl8702** [comment]
@Guanchishan  OK

**Comment by ztl8702** [comment]
![Screen Shot 2020-07-22 at 10 04 09 pm](https://user-images.githubusercontent.com/2714446/88186118-5ea83080-cc67-11ea-8f00-869258b80627.png)

贡献者页面可以搞一个这种头像墙模式

**Comment by Guanchishan** [comment]
突出贡献者头像墙也许可以整这式儿的：https://github.com/Mayandev/notion-avatar
